all: shmserver shmclient shmserver1 shmclient1 shmserver2 shmclient2 shmserver3 \
	shmclient3 shmserver4 shmclient4 shmserver5 shmclient5 shmserver6 \
	shmclient6
shmserver6: shmserver6.o
	gcc -o shmserver6 shmserver6.o

shmserver6.o: shmserver6.c
	gcc -o shmserver6.o -c shmserver6.c

shmclient6: shmclient6.o
	gcc -o shmclient6 shmclient6.o

shmclient6.o: shmclient6.c
	gcc -o shmclient6.o -c shmclient6.c

shmserver5: shmserver5.o
	gcc -o shmserver5 shmserver5.o

shmserver5.o: shmserver5.c
	gcc -o shmserver5.o -c shmserver5.c

shmclient5: shmclient5.o
	gcc -o shmclient5 shmclient5.o

shmclient5.o: shmclient5.c
	gcc -o shmclient5.o -c shmclient5.c

shmserver4: shmserver4.o
	gcc -o shmserver4 shmserver4.o

shmserver4.o: shmserver4.c
	gcc -o shmserver4.o -c shmserver4.c

shmclient4: shmclient4.o
	gcc -o shmclient4 shmclient4.o

shmclient4.o: shmclient4.c
	gcc -o shmclient4.o -c shmclient4.c

shmserver3: shmserver3.o
	gcc -o shmserver3 shmserver3.o

shmserver3.o: shmserver3.c
	gcc -o shmserver3.o -c shmserver3.c

shmclient3: shmclient3.o
	gcc -o shmclient3 shmclient3.o

shmclient3.o: shmclient3.c
	gcc -o shmclient3.o -c shmclient3.c

shmserver2: shmserver2.o
	gcc -o shmserver2 shmserver2.o

shmserver2.o: shmserver2.c
	gcc -o shmserver2.o -c shmserver2.c

shmclient2: shmclient2.o
	gcc -o shmclient2 shmclient2.o

shmclient2.o: shmclient2.c
	gcc -o shmclient2.o -c shmclient2.c

shmserver1: shmserver1.o
	gcc -o shmserver1 shmserver1.o

shmserver1.o: shmserver1.c
	gcc -o shmserver1.o -c shmserver1.c

shmclient1: shmclient1.o
	gcc -o shmclient1 shmclient1.o

shmclient1.o: shmclient1.c
	gcc -o shmclient1.o -c shmclient1.c

shmserver: shmserver.o
	gcc -o shmserver shmserver.o

shmserver.o: shmserver.c
	gcc -o shmserver.o -c shmserver.c

shmclient: shmclient.o
	gcc -o shmclient shmclient.o

shmclient.o: shmclient.c
	gcc -o shmclient.o -c shmclient.c

clean:
	rm *.o
